<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Estado;
use App\Models\Ciudade;

class VnzSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Estado::create(['name' => 'Amazonas']);
        Estado::create(['name' => 'Anzoátegui']);
        Estado::create(['name' => 'Apure']);
        Estado::create(['name' => 'Aragua']);
        Estado::create(['name' => 'Barinas']);
        Estado::create(['name' => 'Bolívar']);
        Estado::create(['name' => 'Carabobo']);
        Estado::create(['name' => 'Cojedes']);
        Estado::create(['name' => 'Delta Amacuro']);
        Estado::create(['name' => 'Falcón']);
        Estado::create(['name' => 'Guárico']);
        Estado::create(['name' => 'Lara']);
        Estado::create(['name' => 'Mérida']);
        Estado::create(['name' => 'Miranda']);
        Estado::create(['name' => 'Monagas']);
        Estado::create(['name' => 'Nueva Esparta']);
        Estado::create(['name' => 'Portuguesa']);
        Estado::create(['name' => 'Sucre']);
        Estado::create(['name' => 'Táchira']);
        Estado::create(['name' => 'Trujillo']);
        Estado::create(['name' => 'La Guaira']);
        Estado::create(['name' => 'Yaracuy']);
        Estado::create(['name' => 'Zulia']);
        Estado::create(['name' => 'Distrito Capital']);
        Estado::create(['name' => 'Dependencias Federales']);

        Ciudade::create(['id_estado' => '1', 'name'=>'Maroa']);
        Ciudade::create(['id_estado'=>'1', 'name' => 'Puerto Ayacucho']);
        Ciudade::create(['id_estado'=>'1', 'name' => 'San Fernando de Atabapo']);
        Ciudade::create(['id_estado'=>'2', 'name' => 'Anaco']);
        Ciudade::create(['id_estado'=>'2', 'name' => 'Aragua de Barcelona']);
        Ciudade::create(['id_estado'=>'2', 'name' => 'Barcelona']);
        Ciudade::create(['id_estado'=>'2', 'name' => 'Boca de Uchire']);
        Ciudade::create(['id_estado'=>'2', 'name' => 'Cantaura']);
        Ciudade::create(['id_estado'=>'2', 'name' => 'Clarines']);
        Ciudade::create(['id_estado' => '2'  , 'name' =>  'El Chaparro']);
        Ciudade::create(['id_estado' => '2'  , 'name' =>  'El Pao Anzoátegui']);
        Ciudade::create(['id_estado' => '2'  , 'name' =>  'El Tigre']);
        Ciudade::create(['id_estado' => '2'  , 'name' =>  'El Tigrito']);
        Ciudade::create(['id_estado' => '2'  , 'name' =>  'Guanape']);
        Ciudade::create(['id_estado' => '2'  , 'name' =>  'Guanta']);
        Ciudade::create(['id_estado' => '2'  , 'name' =>  'Lechería']);
        Ciudade::create(['id_estado' => '2'  , 'name' =>  'Onoto']);
        Ciudade::create(['id_estado' => '2'  , 'name' =>  'Pariaguán']);
        Ciudade::create(['id_estado' => '2'  , 'name' =>  'Píritu']);
        Ciudade::create(['id_estado' => '2'  , 'name' =>  'Puerto La Cruz']);
        Ciudade::create(['id_estado' => '2'  , 'name' =>  'Puerto Píritu']);
        Ciudade::create(['id_estado' => '2'  , 'name' =>  'Sabana de Uchire']);
        Ciudade::create(['id_estado' => '2'  , 'name' =>  'San Mateo Anzoátegui']);
        Ciudade::create(['id_estado' => '2'  , 'name' =>  'San Pablo Anzoátegui']);
        Ciudade::create(['id_estado' => '2'  , 'name' =>  'San Tomé']);
        Ciudade::create(['id_estado' => '2'  , 'name' =>  'Santa Ana de Anzoátegui']);
        Ciudade::create(['id_estado' => '2'  , 'name' =>  'Santa Fe Anzoátegui']);
        Ciudade::create(['id_estado' => '2'  , 'name' =>  'Santa Rosa']);
        Ciudade::create(['id_estado' => '2'  , 'name' =>  'Soledad']);
        Ciudade::create(['id_estado' => '2'  , 'name' =>  'Urica']);
        Ciudade::create(['id_estado' => '2'  , 'name' =>  'Valle de Guanape']);
        Ciudade::create(['id_estado' => '3'  , 'name' =>  'Achaguas']);
        Ciudade::create(['id_estado' => '3'  , 'name' =>  'Biruaca']);
        Ciudade::create(['id_estado' => '3'  , 'name' =>  'Bruzual']);
        Ciudade::create(['id_estado' => '3'  , 'name' =>  'El Amparo']);
        Ciudade::create(['id_estado' => '3'  , 'name' =>  'El Nula']);
        Ciudade::create(['id_estado' => '3'  , 'name' =>  'Elorza']);
        Ciudade::create(['id_estado' => '3'  , 'name' =>  'Guasdualito']);
        Ciudade::create(['id_estado' => '3'  , 'name' =>  'Mantecal']);
        Ciudade::create(['id_estado' => '3'  , 'name' =>  'Puerto Páez']);
        Ciudade::create(['id_estado' => '3'  , 'name' =>  'San Fernando de Apure']);
        Ciudade::create(['id_estado' => '3'  , 'name' =>  'San Juan de Payara']);
        Ciudade::create(['id_estado' => '4'  , 'name' =>  'Barbacoas']);
        Ciudade::create(['id_estado' => '4'  , 'name' =>  'Cagua']);
        Ciudade::create(['id_estado' => '4'  , 'name' =>  'Camatagua']);
        Ciudade::create(['id_estado' => '4'  , 'name' =>  'Choroní']);
        Ciudade::create(['id_estado' => '4'  , 'name' =>  'Colonia Tovar']);
        Ciudade::create(['id_estado' => '4'  , 'name' =>  'El Consejo']);
        Ciudade::create(['id_estado' => '4'  , 'name' =>  'La Victoria']);
        Ciudade::create(['id_estado' => '4'  , 'name' =>  'Las Tejerías']);
        Ciudade::create(['id_estado' => '4'  , 'name' =>  'Magdaleno']);
        Ciudade::create(['id_estado' => '4'  , 'name' =>  'Maracay']);
        Ciudade::create(['id_estado' => '4'  , 'name' =>  'Ocumare de La Costa']);
        Ciudade::create(['id_estado' => '4'  , 'name' =>  'Palo Negro']);
        Ciudade::create(['id_estado' => '4'  , 'name' =>  'San Casimiro']);
        Ciudade::create(['id_estado' => '4'  , 'name' =>  'San Mateo']);
        Ciudade::create(['id_estado' => '4'  , 'name' =>  'San Sebastián']);
        Ciudade::create(['id_estado' => '4'  , 'name' =>  'Santa Cruz de Aragua']);
        Ciudade::create(['id_estado' => '4'  , 'name' =>  'Tocorón']);
        Ciudade::create(['id_estado' => '4'  , 'name' =>  'Turmero']);
        Ciudade::create(['id_estado' => '4'  , 'name' =>  'Villa de Cura']);
        Ciudade::create(['id_estado' => '4'  , 'name' =>  'Zuata']);
        Ciudade::create(['id_estado' => '5'  , 'name' =>  'Barinas']);
        Ciudade::create(['id_estado' => '5'  , 'name' =>  'Barinitas']);
        Ciudade::create(['id_estado' => '5'  , 'name' =>  'Barrancas']);
        Ciudade::create(['id_estado' => '5'  , 'name' =>  'Calderas']);
        Ciudade::create(['id_estado' => '5'  , 'name' =>  'Capitanejo']);
        Ciudade::create(['id_estado' => '5'  , 'name' =>  'Ciudad Bolivia']);
        Ciudade::create(['id_estado' => '5'  , 'name' =>  'El Cantón']);
        Ciudade::create(['id_estado' => '5'  , 'name' =>  'Las Veguitas']);
        Ciudade::create(['id_estado' => '5'  , 'name' =>  'Libertad de Barinas']);
        Ciudade::create(['id_estado' => '5'  , 'name' =>  'Sabaneta']);
        Ciudade::create(['id_estado' => '5'  , 'name' =>  'Santa Bárbara de Barinas']);
        Ciudade::create(['id_estado' => '5'  , 'name' =>  'Socopó']);
        Ciudade::create(['id_estado' => '6'  , 'name' =>  'Caicara del Orinoco']);
        Ciudade::create(['id_estado' => '6'  , 'name' =>  'Canaima']);
        Ciudade::create(['id_estado' => '6'  , 'name' =>  'Ciudad Bolívar']);
        Ciudade::create(['id_estado' => '6'  , 'name' =>  'Ciudad Piar']);
        Ciudade::create(['id_estado' => '6'  , 'name' =>  'El Callao']);
        Ciudade::create(['id_estado' => '6'  , 'name' =>  'El Dorado']);
        Ciudade::create(['id_estado' => '6'  , 'name' =>  'El Manteco']);
        Ciudade::create(['id_estado' => '6'  , 'name' =>  'El Palmar']);
        Ciudade::create(['id_estado' => '6'  , 'name' =>  'El Pao']);
        Ciudade::create(['id_estado' => '6'  , 'name' =>  'Guasipati']);
        Ciudade::create(['id_estado' => '6'  , 'name' =>  'Guri']);
        Ciudade::create(['id_estado' => '6'  , 'name' =>  'La Paragua']);
        Ciudade::create(['id_estado' => '6'  , 'name' =>  'Matanzas']);
        Ciudade::create(['id_estado' => '6' , 'name' => 'Puerto Ordaz']);
        Ciudade::create(['id_estado' => '6' , 'name' => 'San Félix']);
        Ciudade::create(['id_estado' => '6' , 'name' => 'Santa Elena de Uairén']);
        Ciudade::create(['id_estado' => '6' , 'name' => 'Tumeremo']);
        Ciudade::create(['id_estado' => '6' , 'name' => 'Unare']);
        Ciudade::create(['id_estado' => '6' , 'name' => 'Upata']);
        Ciudade::create(['id_estado' => '7' , 'name' => 'Bejuma']);
        Ciudade::create(['id_estado' => '7' , 'name' => 'Belén']);
        Ciudade::create(['id_estado' => '7' , 'name' => 'Campo de Carabobo']);
        Ciudade::create(['id_estado' => '7' , 'name' => 'Canoabo']);
        Ciudade::create(['id_estado' => '7' , 'name' => 'Central Tacarigua']);
        Ciudade::create(['id_estado' => '7' , 'name' => 'Chirgua']);
        Ciudade::create(['id_estado' => '7' , 'name' => 'Ciudad Alianza']);
        Ciudade::create(['id_estado' => '7' , 'name' => 'El Palito']);
        Ciudade::create(['id_estado' => '7' , 'name' => 'Guacara']);
        Ciudade::create(['id_estado' => '7' , 'name' => 'Guigue']);
        Ciudade::create(['id_estado' => '7' , 'name' => 'Las Trincheras']);
        Ciudade::create(['id_estado' => '7' , 'name' => 'Los Guayos']);
        Ciudade::create(['id_estado' => '7' , 'name' => 'Mariara']);
        Ciudade::create(['id_estado' => '7' , 'name' => 'Miranda']);
        Ciudade::create(['id_estado' => '7' , 'name' => 'Montalbán']);
        Ciudade::create(['id_estado' => '7' , 'name' => 'Morón']);
        Ciudade::create(['id_estado' => '7' , 'name' => 'Naguanagua']);
        Ciudade::create(['id_estado' => '7' , 'name' => 'Puerto Cabello']);
        Ciudade::create(['id_estado' => '7' , 'name' => 'San Joaquín']);
        Ciudade::create(['id_estado' => '7' , 'name' => 'Tocuyito']);
        Ciudade::create(['id_estado' => '7' , 'name' => 'Urama']);
        Ciudade::create(['id_estado' => '7' , 'name' => 'Valencia']);
        Ciudade::create(['id_estado' => '7' , 'name' => 'Vigirimita']);
        Ciudade::create(['id_estado' => '8' , 'name' => 'Aguirre']);
        Ciudade::create(['id_estado' => '8' , 'name' => 'Apartaderos Cojedes']);
        Ciudade::create(['id_estado' => '8' , 'name' => 'Arismendi']);
        Ciudade::create(['id_estado' => '8' , 'name' => 'Camuriquito']);
        Ciudade::create(['id_estado' => '8' , 'name' => 'El Baúl']);
        Ciudade::create(['id_estado' => '8' , 'name' => 'El Limón']);
        Ciudade::create(['id_estado' => '8' , 'name' => 'El Pao Cojedes']);
        Ciudade::create(['id_estado' => '8' , 'name' => 'El Socorro']);
        Ciudade::create(['id_estado' => '8' , 'name' => 'La Aguadita']);
        Ciudade::create(['id_estado' => '8' , 'name' => 'Las Vegas']);
        Ciudade::create(['id_estado' => '8' , 'name' => 'Libertad de Cojedes']);
        Ciudade::create(['id_estado' => '8' , 'name' => 'Mapuey']);
        Ciudade::create(['id_estado' => '8' , 'name' => 'Piñedo']);
        Ciudade::create(['id_estado' => '8' , 'name' => 'Samancito']);
        Ciudade::create(['id_estado' => '8' , 'name' => 'San Carlos']);
        Ciudade::create(['id_estado' => '8' , 'name' => 'Sucre']);
        Ciudade::create(['id_estado' => '8' , 'name' => 'Tinaco']);
        Ciudade::create(['id_estado' => '8' , 'name' => 'Tinaquillo']);
        Ciudade::create(['id_estado' => '8' , 'name' => 'Vallecito']);
        Ciudade::create(['id_estado' => '9' , 'name' => 'Tucupita']);
        Ciudade::create(['id_estado' => '24' , 'name' => 'Caracas']);
        Ciudade::create(['id_estado' => '24' , 'name' => 'El Junquito']);
        Ciudade::create(['id_estado' => '10' , 'name' => 'Adícora']);
        Ciudade::create(['id_estado' => '10' , 'name' => 'Boca de Aroa']);
        Ciudade::create(['id_estado' => '10' , 'name' => 'Cabure']);
        Ciudade::create(['id_estado' => '10' , 'name' => 'Capadare']);
        Ciudade::create(['id_estado' => '10' , 'name' => 'Capatárida']);
        Ciudade::create(['id_estado' => '10' , 'name' => 'Chichiriviche']);
        Ciudade::create(['id_estado' => '10' , 'name' => 'Churuguara']);
        Ciudade::create(['id_estado' => '10' , 'name' => 'Coro']);
        Ciudade::create(['id_estado' => '10' , 'name' => 'Cumarebo']);
        Ciudade::create(['id_estado' => '10' , 'name' => 'Dabajuro']);
        Ciudade::create(['id_estado' => '10' , 'name' => 'Judibana']);
        Ciudade::create(['id_estado' => '10' , 'name' => 'La Cruz de Taratara']);
        Ciudade::create(['id_estado' => '10' , 'name' => 'La Vela de Coro']);
        Ciudade::create(['id_estado' => '10' , 'name' => 'Los Taques']);
        Ciudade::create(['id_estado' => '10' , 'name' => 'Maparari']);
        Ciudade::create(['id_estado' => '10' , 'name' => 'Mene de Mauroa']);
        Ciudade::create(['id_estado' => '10' , 'name' => 'Mirimire']);
        Ciudade::create(['id_estado' => '10' , 'name' => 'Pedregal']);
        Ciudade::create(['id_estado' => '10' , 'name' => 'Píritu Falcón']);
        Ciudade::create(['id_estado' => '10' , 'name' => 'Pueblo Nuevo Falcón']);
        Ciudade::create(['id_estado' => '10' , 'name' => 'Puerto Cumarebo']);
        Ciudade::create(['id_estado' => '10' , 'name' => 'Punta Cardón']);
        Ciudade::create(['id_estado' => '10' , 'name' => 'Punto Fijo']);
        Ciudade::create(['id_estado' => '10' , 'name' => 'San Juan de Los Cayos']);
        Ciudade::create(['id_estado' => '10' , 'name' => 'San Luis']);
        Ciudade::create(['id_estado' => '10' , 'name' => 'Santa Ana Falcón']);
        Ciudade::create(['id_estado' => '10' , 'name' => 'Santa Cruz De Bucaral']);
        Ciudade::create(['id_estado' => '10' , 'name' => 'Tocopero']);
        Ciudade::create(['id_estado' => '10' , 'name' => 'Tocuyo de La Costa']);
        Ciudade::create(['id_estado' => '10' , 'name' => 'Tucacas']);
        Ciudade::create(['id_estado' => '10' , 'name' => 'Yaracal']);
        Ciudade::create(['id_estado' => '11' , 'name' => 'Altagracia de Orituco']);
        Ciudade::create(['id_estado' => '11' , 'name' => 'Cabruta']);
        Ciudade::create(['id_estado' => '11' , 'name' => 'Calabozo']);
        Ciudade::create(['id_estado' => '11' , 'name' => 'Camaguán']);
        Ciudade::create(['id_estado' => '11' , 'name' => 'Chaguaramas Guárico']);
        Ciudade::create(['id_estado' => '11' , 'name' => 'El Socorro']);
        Ciudade::create(['id_estado' => '11' , 'name' => 'El Sombrero']);
        Ciudade::create(['id_estado' => '11' , 'name' => 'Las Mercedes de Los Llanos']);
        Ciudade::create(['id_estado' => '11' , 'name' => 'Lezama']);
        Ciudade::create(['id_estado' => '11' , 'name' => 'Onoto']);
        Ciudade::create(['id_estado' => '11' , 'name' => 'Ortíz']);
        Ciudade::create(['id_estado' => '11' , 'name' => 'San José de Guaribe']);
        Ciudade::create(['id_estado' => '11' , 'name' => 'San Juan de Los Morros']);
        Ciudade::create(['id_estado' => '11' , 'name' => 'San Rafael de Laya']);
        Ciudade::create(['id_estado' => '11' , 'name' => 'Santa María de Ipire']);
        Ciudade::create(['id_estado' => '11' , 'name' => 'Tucupido']);
        Ciudade::create(['id_estado' => '11' , 'name' => 'Valle de La Pascua']);
        Ciudade::create(['id_estado' => '11' , 'name' => 'Zaraza']);
        Ciudade::create(['id_estado' => '12' , 'name' => 'Aguada Grande']);
        Ciudade::create(['id_estado' => '12' , 'name' => 'Atarigua']);
        Ciudade::create(['id_estado' => '12' , 'name' => 'Barquisimeto']);
        Ciudade::create(['id_estado' => '12' , 'name' => 'Bobare']);
        Ciudade::create(['id_estado' => '12' , 'name' => 'Cabudare']);
        Ciudade::create(['id_estado' => '12' , 'name' => 'Carora']);
        Ciudade::create(['id_estado' => '12' , 'name' => 'Cubiro']);
        Ciudade::create(['id_estado' => '12' , 'name' => 'Cují']);
        Ciudade::create(['id_estado' => '12' , 'name' => 'Duaca']);
        Ciudade::create(['id_estado' => '12' , 'name' => 'El Manzano']);
        Ciudade::create(['id_estado' => '12' , 'name' => 'El Tocuyo']);
        Ciudade::create(['id_estado' => '12' , 'name' => 'Guaríco']);
        Ciudade::create(['id_estado' => '12' , 'name' => 'Humocaro Alto']);
        Ciudade::create(['id_estado' => '12' , 'name' => 'Humocaro Bajo']);
        Ciudade::create(['id_estado' => '12' , 'name' => 'La Miel']);
        Ciudade::create(['id_estado' => '12' , 'name' => 'Moroturo']);
        Ciudade::create(['id_estado' => '12' , 'name' => 'Quíbor']);
        Ciudade::create(['id_estado' => '12' , 'name' => 'Río Claro']);
        Ciudade::create(['id_estado' => '12' , 'name' => 'Sanare']);
        Ciudade::create(['id_estado' => '12' , 'name' => 'Santa Inés']);
        Ciudade::create(['id_estado' => '12' , 'name' => 'Sarare']);
        Ciudade::create(['id_estado' => '12' , 'name' => 'Siquisique']);
        Ciudade::create(['id_estado' => '12' , 'name' => 'Tintorero']);
        Ciudade::create(['id_estado' => '13' , 'name' => 'Apartaderos Mérida']);
        Ciudade::create(['id_estado' => '13' , 'name' => 'Arapuey']);
        Ciudade::create(['id_estado' => '13' , 'name' => 'Bailadores']);
        Ciudade::create(['id_estado' => '13' , 'name' => 'Caja Seca']);
        Ciudade::create(['id_estado' => '13' , 'name' => 'Canaguá']);
        Ciudade::create(['id_estado' => '13' , 'name' => 'Chachopo']);
        Ciudade::create(['id_estado' => '13' , 'name' => 'Chiguara']);
        Ciudade::create(['id_estado' => '13' , 'name' => 'Ejido']);
        Ciudade::create(['id_estado' => '13' , 'name' => 'El Vigía']);
        Ciudade::create(['id_estado' => '13' , 'name' => 'La Azulita']);
        Ciudade::create(['id_estado' => '13' , 'name' => 'La Playa']);
        Ciudade::create(['id_estado' => '13' , 'name' => 'Lagunillas Mérida']);
        Ciudade::create(['id_estado' => '13' , 'name' => 'Mérida']);
        Ciudade::create(['id_estado' => '13' , 'name' => 'Mesa de Bolívar']);
        Ciudade::create(['id_estado' => '13' , 'name' => 'Mucuchíes']);
        Ciudade::create(['id_estado' => '13' , 'name' => 'Mucujepe']);
        Ciudade::create(['id_estado' => '13' , 'name' => 'Mucuruba']);
        Ciudade::create(['id_estado' => '13' , 'name' => 'Nueva Bolivia']);
        Ciudade::create(['id_estado' => '13' , 'name' => 'Palmarito']);
        Ciudade::create(['id_estado' => '13' , 'name' => 'Pueblo Llano']);
        Ciudade::create(['id_estado' => '13' , 'name' => 'Santa Cruz de Mora']);
        Ciudade::create(['id_estado' => '13' , 'name' => 'Santa Elena de Arenales']);
        Ciudade::create(['id_estado' => '13' , 'name' => 'Santo Domingo']);
        Ciudade::create(['id_estado' => '13' , 'name' => 'Tabáy']);
        Ciudade::create(['id_estado' => '13' , 'name' => 'Timotes']);
        Ciudade::create(['id_estado' => '13' , 'name' => 'Torondoy']);
        Ciudade::create(['id_estado' => '13' , 'name' => 'Tovar']);
        Ciudade::create(['id_estado' => '13' , 'name' => 'Tucani']);
        Ciudade::create(['id_estado' => '13' , 'name' => 'Zea']);
        Ciudade::create(['id_estado' => '14' , 'name' => 'Araguita']);
        Ciudade::create(['id_estado' => '14' , 'name' => 'Carrizal']);
        Ciudade::create(['id_estado' => '14' , 'name' => 'Caucagua']);
        Ciudade::create(['id_estado' => '14' , 'name' => 'Chaguaramas Miranda']);
        Ciudade::create(['id_estado' => '14' , 'name' => 'Charallave']);
        Ciudade::create(['id_estado' => '14' , 'name' => 'Chirimena']);
        Ciudade::create(['id_estado' => '14' , 'name' => 'Chuspa']);
        Ciudade::create(['id_estado' => '14' , 'name' => 'Cúa']);
        Ciudade::create(['id_estado' => '14' , 'name' => 'Cupira']);
        Ciudade::create(['id_estado' => '14' , 'name' => 'Curiepe']);
        Ciudade::create(['id_estado' => '14' , 'name' => 'El Guapo']);
        Ciudade::create(['id_estado' => '14' , 'name' => 'El Jarillo']);
        Ciudade::create(['id_estado' => '14' , 'name' => 'Filas de Mariche']);
        Ciudade::create(['id_estado' => '14' , 'name' => 'Guarenas']);
        Ciudade::create(['id_estado' => '14' , 'name' => 'Guatire']);
        Ciudade::create(['id_estado' => '14' , 'name' => 'Higuerote']);
        Ciudade::create(['id_estado' => '14' , 'name' => 'Los Anaucos']);
        Ciudade::create(['id_estado' => '14' , 'name' => 'Los Teques']);
        Ciudade::create(['id_estado' => '14' , 'name' => 'Ocumare del Tuy']);
        Ciudade::create(['id_estado' => '14' , 'name' => 'Panaquire']);
        Ciudade::create(['id_estado' => '14' , 'name' => 'Paracotos']);
        Ciudade::create(['id_estado' => '14' , 'name' => 'Río Chico']);
        Ciudade::create(['id_estado' => '14' , 'name' => 'San Antonio de Los Altos']);
        Ciudade::create(['id_estado' => '14' , 'name' => 'San Diego de Los Altos']);
        Ciudade::create(['id_estado' => '14' , 'name' => 'San Fernando del Guapo']);
        Ciudade::create(['id_estado' => '14' , 'name' => 'San Francisco de Yare']);
        Ciudade::create(['id_estado' => '14' , 'name' => 'San José de Los Altos']);
        Ciudade::create(['id_estado' => '14' , 'name' => 'San José de Río Chico']);
        Ciudade::create(['id_estado' => '14' , 'name' => 'San Pedro de Los Altos']);
        Ciudade::create(['id_estado' => '14' , 'name' => 'Santa Lucía']);
        Ciudade::create(['id_estado' => '14' , 'name' => 'Santa Teresa']);
        Ciudade::create(['id_estado' => '14' , 'name' => 'Tacarigua de La Laguna']);
        Ciudade::create(['id_estado' => '14' , 'name' => 'Tacarigua de Mamporal']);
        Ciudade::create(['id_estado' => '14' , 'name' => 'Tácata']);
        Ciudade::create(['id_estado' => '14' , 'name' => 'Turumo']);
        Ciudade::create(['id_estado' => '15' , 'name' => 'Aguasay']);
        Ciudade::create(['id_estado' => '15' , 'name' => 'Aragua de Maturín']);
        Ciudade::create(['id_estado' => '15' , 'name' => 'Barrancas del Orinoco']);
        Ciudade::create(['id_estado' => '15' , 'name' => 'Caicara de Maturín']);
        Ciudade::create(['id_estado' => '15' , 'name' => 'Caripe']);
        Ciudade::create(['id_estado' => '15' , 'name' => 'Caripito']);
        Ciudade::create(['id_estado' => '15' , 'name' => 'Chaguaramal']);
        Ciudade::create(['id_estado' => '15' , 'name' => 'Chaguaramas Monagas']);
        Ciudade::create(['id_estado' => '15' , 'name' => 'El Furrial']);
        Ciudade::create(['id_estado' => '15' , 'name' => 'El Tejero']);
        Ciudade::create(['id_estado' => '15' , 'name' => 'Jusepín']);
        Ciudade::create(['id_estado' => '15' , 'name' => 'La Toscana']);
        Ciudade::create(['id_estado' => '15' , 'name' => 'Maturín']);
        Ciudade::create(['id_estado' => '15' , 'name' => 'Miraflores']);
        Ciudade::create(['id_estado' => '15' , 'name' => 'Punta de Mata']);
        Ciudade::create(['id_estado' => '15' , 'name' => 'Quiriquire']);
        Ciudade::create(['id_estado' => '15' , 'name' => 'San Antonio de Maturín']);
        Ciudade::create(['id_estado' => '15' , 'name' => 'San Vicente Monagas']);
        Ciudade::create(['id_estado' => '15' , 'name' => 'Santa Bárbara']);
        Ciudade::create(['id_estado' => '15' , 'name' => 'Temblador']);
        Ciudade::create(['id_estado' => '15' , 'name' => 'Teresen']);
        Ciudade::create(['id_estado' => '15' , 'name' => 'Uracoa']);
        Ciudade::create(['id_estado' => '16' , 'name' => 'Altagracia']);
        Ciudade::create(['id_estado' => '16' , 'name' => 'Boca de Pozo']);
        Ciudade::create(['id_estado' => '16' , 'name' => 'Boca de Río']);
        Ciudade::create(['id_estado' => '16' , 'name' => 'El Espinal']);
        Ciudade::create(['id_estado' => '16' , 'name' => 'El Valle del Espíritu Santo']);
        Ciudade::create(['id_estado' => '16' , 'name' => 'El Yaque']);
        Ciudade::create(['id_estado' => '16' , 'name' => 'Juangriego']);
        Ciudade::create(['id_estado' => '16' , 'name' => 'La Asunción']);
        Ciudade::create(['id_estado' => '16' , 'name' => 'La Guardia']);
        Ciudade::create(['id_estado' => '16' , 'name' => 'Pampatar']);
        Ciudade::create(['id_estado' => '16' , 'name' => 'Porlamar']);
        Ciudade::create(['id_estado' => '16' , 'name' => 'Puerto Fermín']);
        Ciudade::create(['id_estado' => '16' , 'name' => 'Punta de Piedras']);
        Ciudade::create(['id_estado' => '16' , 'name' => 'San Francisco de Macanao']);
        Ciudade::create(['id_estado' => '16' , 'name' => 'San Juan Bautista']);
        Ciudade::create(['id_estado' => '16' , 'name' => 'San Pedro de Coche']);
        Ciudade::create(['id_estado' => '16' , 'name' => 'Santa Ana de Nueva Esparta']);
        Ciudade::create(['id_estado' => '16' , 'name' => 'Villa Rosa']);
        Ciudade::create(['id_estado' => '17' , 'name' => 'Acarigua']);
        Ciudade::create(['id_estado' => '17' , 'name' => 'Agua Blanca']);
        Ciudade::create(['id_estado' => '17' , 'name' => 'Araure']);
        Ciudade::create(['id_estado' => '17' , 'name' => 'Biscucuy']);
        Ciudade::create(['id_estado' => '17' , 'name' => 'Boconoito']);
        Ciudade::create(['id_estado' => '17' , 'name' => 'Campo Elías']);
        Ciudade::create(['id_estado' => '17' , 'name' => 'Chabasquén']);
        Ciudade::create(['id_estado' => '17' , 'name' => 'Guanare']);
        Ciudade::create(['id_estado' => '17' , 'name' => 'Guanarito']);
        Ciudade::create(['id_estado' => '17' , 'name' => 'La Aparición']);
        Ciudade::create(['id_estado' => '17' , 'name' => 'La Misión']);
        Ciudade::create(['id_estado' => '17' , 'name' => 'Mesa de Cavacas']);
        Ciudade::create(['id_estado' => '17' , 'name' => 'Ospino']);
        Ciudade::create(['id_estado' => '17' , 'name' => 'Papelón']);
        Ciudade::create(['id_estado' => '17' , 'name' => 'Payara']);
        Ciudade::create(['id_estado' => '17' , 'name' => 'Pimpinela']);
        Ciudade::create(['id_estado' => '17' , 'name' => 'Píritu de Portuguesa']);
        Ciudade::create(['id_estado' => '17' , 'name' => 'San Rafael de Onoto']);
        Ciudade::create(['id_estado' => '17' , 'name' => 'Santa Rosalía']);
        Ciudade::create(['id_estado' => '17' , 'name' => 'Turén']);
        Ciudade::create(['id_estado' => '18' , 'name' => 'Altos de Sucre']);
        Ciudade::create(['id_estado' => '18' , 'name' => 'Araya']);
        Ciudade::create(['id_estado' => '18' , 'name' => 'Cariaco']);
        Ciudade::create(['id_estado' => '18' , 'name' => 'Carúpano']);
        Ciudade::create(['id_estado' => '18' , 'name' => 'Casanay']);
        Ciudade::create(['id_estado' => '18' , 'name' => 'Cumaná']);
        Ciudade::create(['id_estado' => '18' , 'name' => 'Cumanacoa']);
        Ciudade::create(['id_estado' => '18' , 'name' => 'El Morro Puerto Santo']);
        Ciudade::create(['id_estado' => '18' , 'name' => 'El Pilar']);
        Ciudade::create(['id_estado' => '18' , 'name' => 'El Poblado']);
        Ciudade::create(['id_estado' => '18' , 'name' => 'Guaca']);
        Ciudade::create(['id_estado' => '18' , 'name' => 'Guiria']);
        Ciudade::create(['id_estado' => '18' , 'name' => 'Irapa']);
        Ciudade::create(['id_estado' => '18' , 'name' => 'Manicuare']);
        Ciudade::create(['id_estado' => '18' , 'name' => 'Mariguitar']);
        Ciudade::create(['id_estado' => '18' , 'name' => 'Río Caribe']);
        Ciudade::create(['id_estado' => '18' , 'name' => 'San Antonio del Golfo']);
        Ciudade::create(['id_estado' => '18' , 'name' => 'San José de Aerocuar']);
        Ciudade::create(['id_estado' => '18' , 'name' => 'San Vicente de Sucre']);
        Ciudade::create(['id_estado' => '18' , 'name' => 'Santa Fe de Sucre']);
        Ciudade::create(['id_estado' => '18' , 'name' => 'Tunapuy']);
        Ciudade::create(['id_estado' => '18' , 'name' => 'Yaguaraparo']);
        Ciudade::create(['id_estado' => '18' , 'name' => 'Yoco']);
        Ciudade::create(['id_estado' => '19' , 'name' => 'Abejales']);
        Ciudade::create(['id_estado' => '19' , 'name' => 'Borota']);
        Ciudade::create(['id_estado' => '19' , 'name' => 'Bramon']);
        Ciudade::create(['id_estado' => '19' , 'name' => 'Capacho']);
        Ciudade::create(['id_estado' => '19' , 'name' => 'Colón']);
        Ciudade::create(['id_estado' => '19' , 'name' => 'Coloncito']);
        Ciudade::create(['id_estado' => '19' , 'name' => 'Cordero']);
        Ciudade::create(['id_estado' => '19' , 'name' => 'El Cobre']);
        Ciudade::create(['id_estado' => '19' , 'name' => 'El Pinal']);
        Ciudade::create(['id_estado' => '19' , 'name' => 'Independencia']);
        Ciudade::create(['id_estado' => '19' , 'name' => 'La Fría']);
        Ciudade::create(['id_estado' => '19' , 'name' => 'La Grita']);
        Ciudade::create(['id_estado' => '19' , 'name' => 'La Pedrera']);
        Ciudade::create(['id_estado' => '19' , 'name' => 'La Tendida']);
        Ciudade::create(['id_estado' => '19' , 'name' => 'Las Delicias']);
        Ciudade::create(['id_estado' => '19' , 'name' => 'Las Hernández']);
        Ciudade::create(['id_estado' => '19' , 'name' => 'Lobatera']);
        Ciudade::create(['id_estado' => '19' , 'name' => 'Michelena']);
        Ciudade::create(['id_estado' => '19' , 'name' => 'Palmira']);
        Ciudade::create(['id_estado' => '19' , 'name' => 'Pregonero']);
        Ciudade::create(['id_estado' => '19' , 'name' => 'Queniquea']);
        Ciudade::create(['id_estado' => '19' , 'name' => 'Rubio']);
        Ciudade::create(['id_estado' => '19' , 'name' => 'San Antonio del Tachira']);
        Ciudade::create(['id_estado' => '19' , 'name' => 'San Cristobal']);
        Ciudade::create(['id_estado' => '19' , 'name' => 'San José de Bolívar']);
        Ciudade::create(['id_estado' => '19' , 'name' => 'San Josecito']);
        Ciudade::create(['id_estado' => '19' , 'name' => 'San Pedro del Río']);
        Ciudade::create(['id_estado' => '19' , 'name' => 'Santa Ana Táchira']);
        Ciudade::create(['id_estado' => '19' , 'name' => 'Seboruco']);
        Ciudade::create(['id_estado' => '19' , 'name' => 'Táriba']);
        Ciudade::create(['id_estado' => '19' , 'name' => 'Umuquena']);
        Ciudade::create(['id_estado' => '19' , 'name' => 'Ureña']);
        Ciudade::create(['id_estado' => '20' , 'name' => 'Batatal']);
        Ciudade::create(['id_estado' => '20' , 'name' => 'Betijoque']);
        Ciudade::create(['id_estado' => '20' , 'name' => 'Boconó']);
        Ciudade::create(['id_estado' => '20' , 'name' => 'Carache']);
        Ciudade::create(['id_estado' => '20' , 'name' => 'Chejende']);
        Ciudade::create(['id_estado' => '20' , 'name' => 'Cuicas']);
        Ciudade::create(['id_estado' => '20' , 'name' => 'El Dividive']);
        Ciudade::create(['id_estado' => '20' , 'name' => 'El Jaguito']);
        Ciudade::create(['id_estado' => '20' , 'name' => 'Escuque']);
        Ciudade::create(['id_estado' => '20' , 'name' => 'Isnotú']);
        Ciudade::create(['id_estado' => '20' , 'name' => 'Jajó']);
        Ciudade::create(['id_estado' => '20' , 'name' => 'La Ceiba']);
        Ciudade::create(['id_estado' => '20' , 'name' => 'La Concepción de Trujllo']);
        Ciudade::create(['id_estado' => '20' , 'name' => 'La Mesa de Esnujaque']);
        Ciudade::create(['id_estado' => '20' , 'name' => 'La Puerta']);
        Ciudade::create(['id_estado' => '20' , 'name' => 'La Quebrada']);
        Ciudade::create(['id_estado' => '20' , 'name' => 'Mendoza Fría']);
        Ciudade::create(['id_estado' => '20' , 'name' => 'Meseta de Chimpire']);
        Ciudade::create(['id_estado' => '20' , 'name' => 'Monay']);
        Ciudade::create(['id_estado' => '20' , 'name' => 'Motatán']);
        Ciudade::create(['id_estado' => '20' , 'name' => 'Pampán']);
        Ciudade::create(['id_estado' => '20' , 'name' => 'Pampanito']);
        Ciudade::create(['id_estado' => '20' , 'name' => 'Sabana de Mendoza']);
        Ciudade::create(['id_estado' => '20' , 'name' => 'San Lázaro']);
        Ciudade::create(['id_estado' => '20' , 'name' => 'Santa Ana de Trujillo']);
        Ciudade::create(['id_estado' => '20' , 'name' => 'Tostós']);
        Ciudade::create(['id_estado' => '20' , 'name' => 'Trujillo']);
        Ciudade::create(['id_estado' => '20' , 'name' => 'Valera']);
        Ciudade::create(['id_estado' => '21' , 'name' => 'Carayaca']);
        Ciudade::create(['id_estado' => '21' , 'name' => 'Litoral']);
        Ciudade::create(['id_estado' => '25' , 'name' => 'Archipiélago Los Roques']);
        Ciudade::create(['id_estado' => '22' , 'name' => 'Aroa']);
        Ciudade::create(['id_estado' => '22' , 'name' => 'Boraure']);
        Ciudade::create(['id_estado' => '22' , 'name' => 'Campo Elías de Yaracuy']);
        Ciudade::create(['id_estado' => '22' , 'name' => 'Chivacoa']);
        Ciudade::create(['id_estado' => '22' , 'name' => 'Cocorote']);
        Ciudade::create(['id_estado' => '22' , 'name' => 'Farriar']);
        Ciudade::create(['id_estado' => '22' , 'name' => 'Guama']);
        Ciudade::create(['id_estado' => '22' , 'name' => 'Marín']);
        Ciudade::create(['id_estado' => '22' , 'name' => 'Nirgua']);
        Ciudade::create(['id_estado' => '22' , 'name' => 'Sabana de Parra']);
        Ciudade::create(['id_estado' => '22' , 'name' => 'Salom']);
        Ciudade::create(['id_estado' => '22' , 'name' => 'San Felipe']);
        Ciudade::create(['id_estado' => '22' , 'name' => 'San Pablo de Yaracuy']);
        Ciudade::create(['id_estado' => '22' , 'name' => 'Urachiche']);
        Ciudade::create(['id_estado' => '22' , 'name' => 'Yaritagua']);
        Ciudade::create(['id_estado' => '22' , 'name' => 'Yumare']);
        Ciudade::create(['id_estado' => '23' , 'name' => 'Bachaquero']);
        Ciudade::create(['id_estado' => '23' , 'name' => 'Bobures']);
        Ciudade::create(['id_estado' => '23' , 'name' => 'Cabimas']);
        Ciudade::create(['id_estado' => '23' , 'name' => 'Campo Concepción']);
        Ciudade::create(['id_estado' => '23' , 'name' => 'Campo Mara']);
        Ciudade::create(['id_estado' => '23' , 'name' => 'Campo Rojo']);
        Ciudade::create(['id_estado' => '23' , 'name' => 'Carrasquero']);
        Ciudade::create(['id_estado' => '23' , 'name' => 'Casigua']);
        Ciudade::create(['id_estado' => '23' , 'name' => 'Chiquinquirá']);
        Ciudade::create(['id_estado' => '23' , 'name' => 'Ciudad Ojeda']);
        Ciudade::create(['id_estado' => '23' , 'name' => 'El Batey']);
        Ciudade::create(['id_estado' => '23' , 'name' => 'El Carmelo']);
        Ciudade::create(['id_estado' => '23' , 'name' => 'El Chivo']);
        Ciudade::create(['id_estado' => '23' , 'name' => 'El Guayabo']);
        Ciudade::create(['id_estado' => '23' , 'name' => 'El Mene']);
        Ciudade::create(['id_estado' => '23' , 'name' => 'El Venado']);
        Ciudade::create(['id_estado' => '23' , 'name' => 'Encontrados']);
        Ciudade::create(['id_estado' => '23' , 'name' => 'Gibraltar']);
        Ciudade::create(['id_estado' => '23' , 'name' => 'Isla de Toas']);
        Ciudade::create(['id_estado' => '23' , 'name' => 'La Concepción del Zulia']);
        Ciudade::create(['id_estado' => '23' , 'name' => 'La Paz']);
        Ciudade::create(['id_estado' => '23' , 'name' => 'La Sierrita']);
        Ciudade::create(['id_estado' => '23' , 'name' => 'Lagunillas del Zulia']);
        Ciudade::create(['id_estado' => '23' , 'name' => 'Las Piedras de Perijá']);
        Ciudade::create(['id_estado' => '23' , 'name' => 'Los Cortijos']);
        Ciudade::create(['id_estado' => '23' , 'name' => 'Machiques']);
        Ciudade::create(['id_estado' => '23' , 'name' => 'Maracaibo']);
        Ciudade::create(['id_estado' => '23' , 'name' => 'Mene Grande']);
        Ciudade::create(['id_estado' => '23' , 'name' => 'Palmarejo']);
        Ciudade::create(['id_estado' => '23' , 'name' => 'Paraguaipoa']);
        Ciudade::create(['id_estado' => '23' , 'name' => 'Potrerito']);
        Ciudade::create(['id_estado' => '23' , 'name' => 'Pueblo Nuevo del Zulia']);
        Ciudade::create(['id_estado' => '23' , 'name' => 'Puertos de Altagracia']);
        Ciudade::create(['id_estado' => '23' , 'name' => 'Punta Gorda']);
        Ciudade::create(['id_estado' => '23' , 'name' => 'Sabaneta de Palma']);
        Ciudade::create(['id_estado' => '23' , 'name' => 'San Francisco']);
        Ciudade::create(['id_estado' => '23' , 'name' => 'San José de Perijá']);
        Ciudade::create(['id_estado' => '23' , 'name' => 'San Rafael del Moján']);
        Ciudade::create(['id_estado' => '23' , 'name' => 'San Timoteo']);
        Ciudade::create(['id_estado' => '23' , 'name' => 'Santa Bárbara Del Zulia']);
        Ciudade::create(['id_estado' => '23' , 'name' => 'Santa Cruz de Mara']);
        Ciudade::create(['id_estado' => '23' , 'name' => 'Santa Cruz del Zulia']);
        Ciudade::create(['id_estado' => '23' , 'name' => 'Santa Rita']);
        Ciudade::create(['id_estado' => '23' , 'name' => 'Sinamaica']);
        Ciudade::create(['id_estado' => '23' , 'name' => 'Tamare']);
        Ciudade::create(['id_estado' => '23' , 'name' => 'Tía Juana']);
        Ciudade::create(['id_estado' => '23' , 'name' => 'Villa del Rosario']);
        Ciudade::create(['id_estado' => '21' , 'name' => 'La Guaira']);
        Ciudade::create(['id_estado' => '21' , 'name' => 'Catia La Mar']);
        Ciudade::create(['id_estado' => '21' , 'name' => 'Macuto']);
        Ciudade::create(['id_estado' => '21' , 'name' => 'Naiguatá']);
        Ciudade::create(['id_estado' => '25' , 'name' => 'Archipiélago Los Monjes']);
        Ciudade::create(['id_estado' => '25' , 'name' => 'Isla La Tortuga y os adyacentes']);
        Ciudade::create(['id_estado' => '25' , 'name' => 'Isla La Sola']);
        Ciudade::create(['id_estado' => '25' , 'name' => 'Islas Los Testigos']);
        Ciudade::create(['id_estado' => '25' , 'name' => 'Islas Los Frailes']);
        Ciudade::create(['id_estado' => '25' , 'name' => 'Isla La Orchila']);
        Ciudade::create(['id_estado' => '25' , 'name' => 'Archipiélago Las Aves']);
        Ciudade::create(['id_estado' => '25' , 'name' => 'Isla de Aves']);
        Ciudade::create(['id_estado' => '25' , 'name' => 'Isla La Blanquilla']);
        Ciudade::create(['id_estado' => '25' , 'name' => 'Isla de Patos']);
        Ciudade::create(['id_estado' => '25' , 'name' => 'Islas Los Hermanos']);


    }
}
